{
 "title": "Service Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=~\"data-broker-service|orchestrator-service\"}[5m])",
     "legendFormat": "{{job}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=~\"data-broker-service|orchestrator-service\"}[5m]) / rate(http_server_requests_seconds_count{job=~\"data-broker-service|orchestrator-service\"}[5m])",
     "legendFormat": "{{job}} - {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"data-broker-service|orchestrator-service\",status!~\"5..\"}[5m])) / sum(rate(http_server_requests_seconds_count{job=~\"data-broker-service|orchestrator-service\"}[5m]))",
     "legendFormat": "Success Rate"
    }
   ]
  }
 ]
}